image: python:3.12

stages:
  - build
  - deploy

cache:
  paths:
    - .venv/
    - .cache/pip/

before_script:
  - python -m venv .venv
  - . .venv/bin/activate
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt

build_site:
  stage: build
  script:
    - . .venv/bin/activate
    - python -m mkdocs build
  artifacts:
    paths:
      - site/
    expire_in: 1 week
  only:
    - main

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache rsync openssh
    - echo "${DEPLOY_KEY}" | openssl base64 -A -d | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ip=$(printf '$STATIC_DEPLOY_URL' "$s" | sed -n 's/.*@\([0-9]\{1,3\}\(\.[0-9]\{1,3\}\)\{3\}\).*/\1/p')
    - echo "Extracted IP: $ip"
    - ssh-keyscan $ip >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "Deploying to $STATIC_DEPLOY_URL"
    - rsync -rav --delete-after ./site/ $STATIC_DEPLOY_URL
  artifacts:
    paths:
      - site/
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
