site_name: Chat.cz - nápověda
site_description: Nápověda pro chatovací server Chat.cz
site_url: https://help.chat.cz

repo_name: GitHub
repo_url: https://github.com/chat-cz/help
edit_uri: edit/main/docs

nav:
  - Úvod: index.md
  - Chat: 
    - Úvod: chat/index.md
    - Místnost: chat/mistnost/index.md
    - Rezervovaná místnost: chat/rezervovana-mistnost.md
  - Diskuze: diskuze/index.md
  - Fotogalerie:
    - Úvod: fotogalerie/index.md
    - Fotka: fotogalerie/fotka.md
  - Obecné: 
    - Úvod: obecne/index.md
    - Admini: obecne/admini.md
    - Ignorování: obecne/ignorovani.md
    - Karma: obecne/karma.md
    - Pravidla: obecne/pravidla.md
    - Výhody přihlášených: obecne/vyhody-prihlasenych.md

theme:
  name: mkdocs
  locale: cs
  user_color_mode_toggle: auto
  custom_dir: custom_theme/

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - markdown.extensions.attr_list

hooks:
  - hooks/copyright.py

plugins:
  - search

