site_name: Chat.cz - nápověda
site_url: https://help.chat.cz

repo_name: GitHub
repo_url: https://github.com/chat-cz/help
edit_uri: edit/main/docs

nav:
  - Úvod: index.md
  - Chat: 
    - Homepage: chat/index.md
    - Místnost: chat/mistnost/index.md

theme:
  name: mkdocs
  locale: cs
  user_color_mode_toggle: auto
  custom_dir: custom_theme/

markdown_extensions:
  - markdown.extensions.attr_list
